CSRP/urls.py
from django import views
from django.urls import path
from CSRP import views

urlpatterns = [
    path('', views.home, name="CSRP-home"),
    path('home/', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('contactus/', views.contactus, name="contactus"),
    path('portal/', views.portal, name="portal"),
    path('register/', views.Register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path("requistionportal/", views.addrequistion, name="Addrequistion"),
    path('requistionform/', views.Requistionform, name="requistionform"),
    path("electricalrequistionform/", views.electricalrequistionform, name="electricalrequistionform"),
    path("requistiondetails/", views.requistiondetails, name="requistiondetails"),
    path("updatesection/", views.update, name="updatesection"),
    path('delete/<int:requistionid>/', views.delete, name='delete'),
    path('logsheetdetails/', views.logsheetdetails, name='logsheetdetails'),
#    path('comments/<int:requistionid>/', views.comments, name='comments'),
    path('feedbackform/', views.feedbackform, name='feedbackform'),
    path('feedbacksdetails/', views.feedbacksdetails, name='feedbacksdetails')
]

NED Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('CSRP.urls'))
]

CSRP/models.py
from django.db import models


# Create your models here.

class UserDetails(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]

    phone_number = models.CharField(max_length=15, blank=True, null=True)  # You might want to validate this further
    telephone_number = models.CharField(max_length=15, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    cnic = models.CharField(max_length=50, blank=True, null=True)
    user = models.IntegerField(blank=True, null=True)

    class Meta:
        app_label = 'CSRP'


class RequistionForm(models.Model):
    DEPARTMENT_CHOICES = [
        ('CED', 'Department of Civil Engineering'),
        ('END', 'Department of Environmental Engineering'),
        ('ARD', 'Department of Architecture & Planning'),
        ('PED', 'Department of Petroleum Engineering'),
        ('UED', 'Department of Urban & Infrastructure Engineering'),
        ('EQD', 'Department of Earthquake Engineering'),
        ('EED', 'Department of Electrical Engineering'),
        ('CIS', 'Department of Computer & Information Systems Engineering'),
        ('ELD', 'Department of Electronic Engineering'),
        ('MED', 'Department of Mechanical Engineering'),
        ('TXD', 'Department of Textile Engineering'),
        ('IMD', 'Department of Industrial & Manufacturing Engineering'),
        ('ATD', 'Department of Automotive & Marine Engineering'),
        ('CSE', 'Department of Computer Science & Software Engineering'),
        ('DMT', 'Department of Mathematics'),
        ('DPH', 'Department of Physics'),
        ('DCY', 'Department of Chemistry'),
        ('HSD', 'Department of Humanities'),
        ('MMD', 'Department of Material Engineering'),
        ('MYD', 'Department of Metallurgical Engineering'),
        ('DEC', 'Department of Chemical Engineering'),
        ('PPD', 'Department of Polymer & Petrochemical Engineering'),
        ('BMD', 'Department of Biomedical Engineering'),
        ('FED', 'Department of Food Engineering'),
        ('EMD', 'Department of Economics & Management Sciences'),
        ('Dean(MME)', 'Dean(MME)'),
        ('Dean(ECE)', 'Dean(MME)'),
        ('Dean(ISH)', 'Dean(MME)'),
        ('Dean(CPE)', 'Dean(MME)'),
        ('Dean(AMS)', 'Dean(MME)'),
        ('VCS', 'Vice Chancellor’s Secretariat'),
        ('QMC/QEC', 'Quality Management Cell/Quality Enhancement Cell'),
        ('RO', 'Registrar Office'),
        ('DOF', 'Directorate of Finance'),
        ('AUD', 'Audit Department'),
        ('DW&S', 'Directorate of Works & Services'),
        ('DPD', 'Directorate of Planning & Development'),
        ('AKL', 'Engr. Abul Kalam Library'),
        ('EXD', 'Examinations Department'),
        ('MLD', 'Medical Department'),
        ('DSA', 'Department of Student Affairs'),
        ('DIL', 'Directorate of Industrial Liaison'),
        ('ITD', 'Information Technology Department'),
        ('NED Academy', 'NED Academy'),
        ('CCEE', 'Centre for Continuing Engineering Education'),
        ('CMPC', 'Centre for Multidisciplinary Postgraduate Courses'),
        ('UAFA', 'University Advancement & Financial Assistance"'),
        ('ORIC', 'DOffice of Research Innovation and Commercialization'),
        ('CINETIC', 'Center of Innovation, Entrepreneurship, Technology Incubation and Commercialization (CINETIC)'),
        ('PC', 'Procurement Cell'),
        ('NED-DICE-EIC', 'NED-DICE-Energy Innovation Centre'),
        ('NULL', 'Not Defined')
    ]
    
    REQUISTION_TYPE_CHOICES = [
        ('CR', 'Civil Requistions'),
        ('ER', 'Electrical Requistions'),
    ]

    department = models.CharField(
        max_length=2000,
        choices=DEPARTMENT_CHOICES,
        default='NULL',
        blank=True,
        null=True
    )

    requistion_type = models.CharField(
        max_length=300,
        choices=REQUISTION_TYPE_CHOICES,
        default='CR',
        blank=True,
        null=True
    )

    user_id = models.CharField(max_length=255)
    requistionsubject = models.CharField(max_length=300, blank=True, null=True)
    noofarticles = models.TextField(max_length=30, blank=True, null=True)
    requistiondescription = models.TextField(max_length=30, blank=True, null=True)
    date = models.DateField(auto_now_add=True)
    assignto = models.TextField(max_length=30, blank=True, null=True)
#    comment = models.TextField(max_length=300, blank=True, null=True)
    designation = models.TextField(max_length=300, blank=True, null=True)
    extensionnumber = models.CharField(max_length=15, blank=True, null=True)
    updatedon = models.DateField(auto_now_add=True)
    updatedtime = models.TimeField(auto_now_add=True, auto_now=False, blank=True)
    time = models.TimeField(auto_now_add=True, auto_now=False, blank=True)
    status = models.TextField(
        max_length=300,
        choices=REQUISTION_TYPE_CHOICES,
        default='OPEN',
        blank=True,
        null=True
    )

    STATUS_CHOICES = [
        ('OPEN', 'Open'),
        ('IP', 'In Progress'),
        ('CLOSED', 'Closed')
    ]

    def __str__(self):
        return f"{self.requistionsubject} - {self.department}"
    
    class Meta:
        app_label = 'CSRP'


#class Comments(models.Model):
#    comment = models.TextField(max_length=300, blank=True, null=True)
#    owner = models.ForeignKey(RequistionForm, on_delete=models.CASCADE)
#    commentsubmiton = models.DateTimeField(auto_now_add=True)
#    commentposter = models.CharField(max_length=300, blank=True, null=True)

#    class Meta:
#        app_label = 'CSRP'

#    def __str__(self):
#        return f"{self.comment}"
    

class FeedbackForm(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    csrno = models.CharField(max_length=15, blank=True, null=True)
    phonenumber = models.CharField(max_length=15, blank=True, null=True)
    message = models.TextField(max_length=30, blank=True, null=True)

    class Meta:
        app_label = 'CSRP'

    def __str__(self):
        return f"{self.feedback}"

CSRP/views.py
import datetime
from datetime import datetime, time, timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string 
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.views.decorators.cache import never_cache
from requests import request, session
from django.contrib import messages
from plyer import notification
from .models import RequistionForm, UserDetails, FeedbackForm

# Create your views here.

def home(request):
    return render(request,"CSRP/home.html")

def about(request):
    return render(request, "CSRP/about.html")

def contactus(request):
    return render(request, "CSRP/contactus.html")

def portal(request):
    return render(request, "CSRP/portal.html")

def Register(request):
    if request.method=='POST':
        first_name = request.POST.get('first_name')
        last_name= request.POST.get('last_name')
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        confirmpassword=request.POST.get('confirmpassword')
        phone_number = request.POST.get('phone_number')
        telephone_number = request.POST.get('telephone_number')
        cnic = request.POST.get('cnic')
        city = request.POST.get('city')
        gender = request.POST.get('gender')

        print(first_name)
        print(last_name)
        print(username)
        print(email)
        print(password)
        print(confirmpassword)
        print(phone_number)
        print(telephone_number)
        print(cnic)
        print(city)
        print(gender)

        if password!=confirmpassword:
            return HttpResponse("Your password and confrom password are not Same!!")
        else:
            user=User.objects.create(
                username=username,
                email=email,
                first_name=first_name,
                last_name=last_name,
            )
            user.set_password(password)
            user.save()
            UserDetails.objects.create(
                phone_number=phone_number,
                telephone_number=telephone_number,
                gender=gender,
                cnic=cnic,
                city=city,
                user=user.id
            )
            return redirect('login')

    return render (request,"CSRP/register.html")


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)  # Use auth_login to log the user in
            return redirect('dashboard')
        else:
            return HttpResponse("Username or Password is incorrect!!!")

    return render(request, "CSRP/login.html")


def logout(request):
    return redirect('login')

@never_cache
@login_required
@require_http_methods(["GET", "POST", "UPDATE"])
def dashboard(request):
    if request.method == "POST":
        # Your existing POST handling logic remains unchanged
        pass

    requistionid = request.GET.get("requistionsubject_id")
        
    if requistionid:
            requistionforms = RequistionForm.objects.filter(
                user_id=request.user.id, id=requistionid
        )

    else:  # Handle GET requests
        # Fetching the requisition forms for non-superuser
        requistionforms = RequistionForm.objects.filter(user_id=request.user.id)

        # If the user is a superuser, adjust the requisition forms accordingly
        if request.user.is_superuser:
            if request.user.is_superuser == 2:
                requistionforms = RequistionForm.objects.filter(department__contains='Electrical')
            elif request.user.is_superuser == 3:
                requistionforms = RequistionForm.objects.filter(department__contains='Civil')
            else:
                requistionforms = RequistionForm.objects.all()
    
    return render(
        request,
        "CSRP/dashboard.html",
        {
            "requistion_forms": requistionforms,

            # Pass other necessary context data as needed
        },
    )


@login_required
def addrequistion(request):
    return render(request, "CSRP/requistionportal.html")


@login_required
def requistionportal(request):
    return render(request, "CSRP/requistionportal.html")


@login_required
def Requistionform(request):
    if request.method == 'POST':
        user = request.POST.get('user_id')
        department= request.POST.get('department')
        requistion_type = request.POST.get('requistion_type')
        requistionsubject = request.POST.get('requistionsubject')
        noofarticles = request.POST.get('noofarticles')
        requistiondescription = request.POST.get('requistiondescription')
        assignto = request.POST.get('assignto')
        comment = request.POST.get('comment')
        comments = request.POST.get('comments')
        designation = request.POST.get('designation')
        extensionnumber = request.POST.get('extensionnumber')

        print(user)
        print(department)
        print(requistion_type)
        print(requistionsubject)
        print(noofarticles)
        print(requistiondescription)
        print(assignto)
        print(comment)
        print(comments)
        print(designation)
        print(extensionnumber)

        requistionform = RequistionForm.objects.create(
            user_id=user,
            department=department,
            requistion_type=requistion_type,
            requistionsubject=requistionsubject,
            noofarticles=noofarticles,
            requistiondescription=requistiondescription,
            assignto=assignto,
            comment=comment,
            comments=comments,
            designation=designation,
            extensionnumber=extensionnumber,
        )
        requistionform.save()
        
        return redirect('dashboard')
    
    requistionform = RequistionForm.objects.filter(user_id=request.user.id)

    return render(request, 'CSRP/requistionform.html', {
        'requistionform': requistionform,
    })


@login_required
def electricalrequistionform(request):
    return render(request, "CSRP/electricalrequistionform.html")


@login_required
def requistiondetails(request):
    if request.method == "GET":
        requistionid = request.GET.get("requistionsubject_id")
        
        requistionforms = RequistionForm.objects.filter(user_id=request.user.id, id=requistionid)

        if request.user.is_superuser:
             requistionforms = RequistionForm.objects.filter(id=requistionid)
        
        first_requistionform = requistionforms.first()
        print(first_requistionform)
        user = User.objects.get(id=first_requistionform.user_id)
        userdetails = UserDetails.objects.get(user=user.id)
        print(user)
        print(userdetails)

    return render(request, "CSRP/requistiondetails.html", {
        'requistion_forms': requistionforms,
        'user': user,
        'userdetails' : userdetails,
    })


@login_required
def update(request):
    if request.method == 'POST':
        status = request.POST.get('status')
        requistionid = request.POST.get('requistionid')
        assign_to = request.POST.get('assign_to')
    #    comment = request.POST.get('comment')

        # Update the fields directly without fetching the queryset
        RequistionForm.objects.filter(id=requistionid).update(
            status=status,
            assignto=assign_to,  # Add this line to update the assign_to field
       #    comment=comment,
            updatedon=datetime.now(),
            updatedtime=datetime.now()
        )
        return redirect("dashboard")
    return render(request, "CSRP/updatesection.html")


def applybutton():
    if request.method == "UPDATE":
        applybutton = RequistionForm.objects.filter(user_id=request.user.id) 


@login_required
def delete(request, requistionid):
    if request.method == 'POST':
        requistion = get_object_or_404(RequistionForm, pk=requistionid)
        requistion.delete()
        return HttpResponseRedirect('dashboard')  # Redirect to the dashboard page
    return HttpResponseRedirect('dashboard')  # Redirect to the dashboard page


@login_required
def logsheetdetails(request):
    if request.method == 'GET':
        requistionforms = RequistionForm.objects.filter(user_id=request.user.id)

        if request.user.is_superuser:
            if request.user.is_superuser == 3:
                requistionforms = RequistionForm.objects.filter(department__contains='Civil')
            elif request.user.is_superuser == 2:
                requistionforms = RequistionForm.objects.filter(department__contains='Electrical')
            else:
                requistionforms = RequistionForm.objects.all()
            # Add more conditions for other superuser cases as needed

    return render(request, "CSRP/logsheetdetails.html", {"requistion_forms": requistionforms,})


#@login_required
#def comments(request, requistionid):
#    print(requistionid)
#    if request.method == "GET":
#        owner = RequistionForm.objects.get(id=requistionid)
#        comments = owner.comments_set.all()
#        return render(request, "CSRP/comments.html", {"comments": comments, "id":requistionid})
#    if request.method == 'POST':
#        comments_txt = request.POST.get('comments')
#        requistionid = request.POST.get('requistionid')
#        # Get the RequistionForm instance
#        owner = RequistionForm.objects.get(id=requistionid)

CSRP/templates/CSRP/about.html
{% extends "CSRP/base.html" %}
{% load static %} 
{% block content %}
{% endblock %}

CSRP/templates/CSRP/register.html
{% extends "CSRP/base.html" %}
{% load static %} 
{% block title %} Register Page {% endblock title %}
{% block content %}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body class="vh-100" style="width: 100%; background: linear-gradient(to top, rgba(0, 0, 0, 0.5) 50%, rgba(0, 0, 0, 0.5) 50%), url(https://startuppakistan.com.pk/wp-content/uploads/2022/10/ned-university-of-engineeri.jpg); background-position: center; background-size: cover; height: 100vh;">
    <nav style="height: 6rem; width: 100vw; background-color: #fff; box-shadow: 0 3px 20px rgba(0, 0, 0, 0.2); display: flex; position: fixed; z-index: 10;">
        <div class="logo" style="cursor: pointer; padding:1vh 6vw; text-align: center;">
          <img src="{% static 'img/NEDlogo.jpg' %}" width="250" height="auto"/>
        </div>
                <ul class="nav-links" style="margin-top: 0; margin-bottom: 0em; padding: 15px 140px; display: flex; list-style: none; width: vw; justify-content: space-evenly; align-items: center; text-transform: uppercase; font-family: 'Inter Tight', sans-serif; font-size: 15px; font-weight: bolder;">
                    <li style="position: relative;"><a href="/home" style="color: black; text-decoration: none; margin: 0 0.7vw;"><i class="fas fa-home" style="color: black;"></i> HOME</a></li>
                    <li style="position: relative;"><a href="/about" style="color: black; text-decoration: none; margin: 0 0.7vw;"><i class="fas fa-info-circle" style="color: black;"></i> ABOUT</a></li>
                    <li style="position: relative;"><a href="/contactus" style="color: black; text-decoration: none; margin: 0 0.7vw;"><i class="fas fa-envelope mx-1" style="color: black;"></i>CONTACT US</a></li>
                </ul>
            </nav>
            <br><br>
    <div class="container py-5 h-100" style="padding-top: 2rem!important;">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-6"> <!-- Adjusted column width -->
            <div class="card shadow-2-strong" style="border-radius: 1rem; background-color: rgba(255, 255, 255, 0.1); box-shadow: 0 0 10px rgba(0, 0, 0, 0.3); backdrop-filter: blur(5px); border-radius: 10px; top: 10px;">
              <div class="card-body p-4 text-center">
                <h3 class="mb-4" style="color: #fff;">Register As A New Member</h3> 
                            <form method="POST">
                                {% csrf_token %}
                                {% if form.errors %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <div id="form_errors">
                                            {% for key, value in form.errors.items %}
                                                <strong>{{ value }}</strong>
                                            {% endfor %}
                                        </div>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endif %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group" style="position: relative;">
                                            <i class="fa fa-user" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                            <input type="text" name="first_name" placeholder="First Name" class="form-control" maxlength="100" required="" id="id_first_name" style="background-color: transparent; color: white; padding-left: 32px;">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group" style="position: relative;">
                                            <i class="fa fa-user" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                            <input type="text" name="last_name" placeholder="Last Name" class="form-control" maxlength="100" required="" id="id_last_name" style="background-color: transparent; color: white; padding-left: 32px;">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group" style="position: relative;">
                                            <i class="fa fa-user" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                            <input type="text" name="username" placeholder="Username" class="form-control" maxlength="100" autofocus="" required="" id="id_username" style="background-color: transparent; color: white; padding-left: 32px;">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group" style="position: relative;">
                                            <i class="fas fa-envelope mx-1" style="position: absolute; left: 6px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                            <input type="text" name="email" placeholder="Email" class="form-control" required id="id_email" style="background-color: transparent; color: white; padding-left: 32px;">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group" style="position: relative;">
                                            <i class="fa fa-city" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                            <input type="text" name="city" placeholder="City" class="form-control" maxlength="100" autofocus="" required="" id="id_city" style="background-color: transparent; color: white; padding-left: 38px;">
                                        </div>
                                    </div>
                                    <div class="col-md-6" style="margin-left: 83px;">
                                        <div class="form-group" style="position: relative;">
                                            <i class="bi bi-person-vcard-fill" style="font-size: 22px; position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                            <input type="text" name="cnic" placeholder="Enter Cnic Number" class="form-control" maxlength="15" autofocus required id="id_cnic" style="background-color: transparent; color: white; padding-left: 40px;">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group" style="position: relative;">
                                            <i class="fa fa-mobile" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                            <input type="text" name="phone_number" placeholder="Phone Number" class="form-control" maxlength="15" autofocus required id="id_phonenumber" style="background-color: transparent; color: white; padding-left: 28px;">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group" style="position: relative;">
                                            <i class="bi bi-telephone" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                            <input type="text" name="telephone_number" placeholder="Telephone Number" class="form-control" maxlength="15" autofocus required id="id_telephonenumber" style="background-color: transparent; color: white; padding-left: 32px;">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group" style="position: relative;">
                                            <div class="input-group">
                                                <i class="fa fa-lock" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                                <input type="password" name="password" placeholder="Password" class="form-control" data-toggle="password" id="password" maxlength="50" required="" style="background-color: transparent; color: white; padding-left: 32px;">
                                                <input type="text" class="form-control" placeholder="Password" maxlength="50" style="display: none; background-color: transparent; color: white;">
                                                <div class="input-group-append" style="cursor: pointer;">
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group" style="position: relative;">
                                            <div class="input-group">
                                                <i class="fa fa-lock" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: white;"></i>
                                                <input type="password" name="confirmpassword" placeholder="Confirm Password" class="form-control" data-toggle="password" id="password" maxlength="50" required="" style="background-color: transparent; color: white; padding-left: 32px;">
                                                <input type="text" class="form-control" placeholder="Confirm Password" maxlength="50" style="display: none;">
                                                <div class="input-group-append" style="cursor: pointer; background-color: transparent; color: white;">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-start align-items-center mb-4 py-2" style="margin-left: 8px;">
                                        <h6 class="mb-0 me-2" style="color: #fff; margin-right: 10px;">Gender:</h6>
                                        <div class="form-check form-check-inline mb-0 me-2" style="color: #fff;">
                                          <input class="form-check-input" type="radio" name="gender" id="maleGender" value="Male" style="margin-top: 3px;"/>
                                          <label class="form-check-label" for="maleGender" style="margin-bottom: 0; margin-top: 1px;">Male</label>
                                        </div>
                                        <div class="form-check form-check-inline mb-0 me-2" style="color: #fff;">
                                            <input class="form-check-input" type="radio" name="gender" id="femaleGender" value="Female" style="margin-top: 3px;"/>
                                            <label class="form-check-label" for="femaleGender" style="margin-bottom: 0; margin-top: 1px;">Female</label>
                                          </div>
                                        <div class="form-check form-check-inline mb-0" style="color: #fff;">
                                          <input class="form-check-input" type="radio" name="gender" id="otherGender" value="Other" style="margin-top: 3px;"/>
                                          <label class="form-check-label" for="otherGender" style="margin-bottom: 0; margin-top: 1px;">Other</label>
                                        </div>
                                    </div>
                                </div> 
                               <div class="text-center">
                                <button class="btn btn-primary" type="submit" style="background-color: #02632c; border-color: #02632c;">Register/رجسٹر کریں</button>
                                <p class="text-center text-muted mt-5 mb-0" style="margin-top: 0.4rem!important; color: #ffffff!important;">Have already an account? <a href="{% url 'login' %}" style="color: #fff;">Login here</a></p>
                             </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
    <style>
    .form-control{
        color: transparent;
        background-color: transparent;
    }
    .form-control::placeholder {
        color: white; /* Change this to the desired color */
    }
    .btn-outline-secondary {
        color: #ffffff;
        border-color: #ffffff;
    }
    </style>
</body>
{% endblock content %}